version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: src/HelloBuild/bin/Release/HelloBuild.*
  name: Release
# enable patching of AssemblyInfo.* files
# https://www.appveyor.com/docs/build-configuration/#assemblyinfo-patching
assembly_info:
  patch: true
  file: ./src/**/AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


init:
  - ps: |
  # Set "build version number"
# credits: https://github.com/appveyor/ci/issues/691
  - ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
     {
       Update-AppveyorBuild -Version "1.$($env:APPVEYOR_REPO_TAG_NAME.substring(6)).0.{build}"
     }
     else
      {
        # hard version if no tag ()
        Update-AppveyorBuild -Version "1.0.1.{build}"
      }
