version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: src/HelloBuild/bin/Release/HelloBuild.exe
  name: HelloBuild

# enable patching of AssemblyInfo.* files
# https://www.appveyor.com/docs/build-configuration/#assemblyinfo-patching
assembly_info:
  patch: true
  file: 'src\**\AssemblyInfo.cs'
  assembly_version: '$(ASSEMBLYBUILDVERSION)'
  assembly_file_version: '$(ASSEMBLYBUILDVERSION)'
  assembly_informational_version: '{version}'


init:  
  - ps: |
      # Set "build version number"
      # credits: https://github.com/appveyor/ci/issues/691

      # Note: build number too big for use in asembly version. 
      # basic version if no tag.
      $productVersion = "1.0.0.$($env:APPVEYOR_BUILD_NUMBER)"
      $assemblyVersion = "1.0.0.0"
      if ($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("test-v"))
      {
        $productVersion = "1.$($env:APPVEYOR_REPO_TAG_NAME.substring(6)).0.$($env:APPVEYOR_BUILD_NUMBER)"
        $assemblyVersion = "1.$($env:APPVEYOR_REPO_TAG_NAME.substring(6)).0.0"
      }
      Write-Host "Set product version: '$productVersion'"
      Write-Host "Set assembly version: '$assemblyVersion'"
      Update-AppveyorBuild -Version "$productVersion"
      $env:ASSEMBLYBUILDVERSION = $assemblyVersion

  - ps: |
     Write-Host "Status"
     Write-Host "Tag Name: '$env:APPVEYOR_REPO_TAG_NAME'"
     Write-Host "PR Number: '$env:APPVEYOR_PULL_REQUEST_NUMBER'"
     Write-Host "Repo Branch: '$env:APPVEYOR_REPO_BRANCH'"
