version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal

artifacts:
- path: src/HelloBuild/bin/Release/HelloBuild.exe
  name: HelloBuild

- path: $env:APPVEYOR_BUILD_FOLDER\MyData.txt
  name: MyData

# enable patching of sdk style csproj files.
# https://www.appveyor.com/docs/build-configuration/#net-core-csproj-files-patching
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(ASSEMBLYBUILDVERSION)'
  package_version: '{version}'
  assembly_version: '$(ASSEMBLYBUILDVERSION)'
  file_version: '$(ASSEMBLYBUILDVERSION)'
  informational_version: '{version}'

environment:
  MyData:
    secure: XEIbuP+EIXTeIM5CxTppzRWSsG1C6iZx9rS0j6K7mGE=

init:  
  - ps: |
     Write-Host "Status"
     Write-Host "Has Tag: '$env:APPVEYOR_REPO_TAG'"
     Write-Host "Tag Name: '$env:APPVEYOR_REPO_TAG_NAME'"
     Write-Host "PR Number: '$env:APPVEYOR_PULL_REQUEST_NUMBER'"
     Write-Host "Repo Branch: '$env:APPVEYOR_REPO_BRANCH'"
  - cmd: dir
  - ps: |
      # Set "build version number"
      # credits: https://github.com/appveyor/ci/issues/691

      # Note: build number too big for use in asembly version. 
      # basic version if no tag.
      $productVersion = "1.0.0.$($env:APPVEYOR_BUILD_NUMBER)"
      $assemblyVersion = "1.0.0.0"
      if ($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("test-v"))
      {
        $productVersion = "1.$($env:APPVEYOR_REPO_TAG_NAME.substring(6)).0.$($env:APPVEYOR_BUILD_NUMBER)"
        $assemblyVersion = "1.$($env:APPVEYOR_REPO_TAG_NAME.substring(6)).0.0"
      }
      Write-Host "Set product version: '$productVersion'"
      Write-Host "Set assembly version: '$assemblyVersion'"
      Update-AppveyorBuild -Version "$productVersion"
      $env:ASSEMBLYBUILDVERSION = $assemblyVersion

before_build:
   - nuget restore src/

after_build:
  - ps: |
      Write-Host "Some data: '$env:MyData'"
  - ps: |
      #Write the secret to a file
      echo "Some data: '$env:MyData'" >> $env:APPVEYOR_BUILD_FOLDER\MyData.txt
