version: 1.0.{build}
configuration: Release
build:
  verbosity: minimal
artifacts:
- path: src/HelloBuild/bin/Release/HelloBuild.exe
  name: Release

# enable patching of AssemblyInfo.* files
# https://www.appveyor.com/docs/build-configuration/#assemblyinfo-patching
assembly_info:
  patch: true
  file: 'src\**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'


init:  
  - ps: |
      # Set "build version number"
      # credits: https://github.com/appveyor/ci/issues/691

      # basic version if no tag.
      $buildVersion = "1.0.0.$($env:APPVEYOR_BUILD_NUMBER)"

      if ($env:APPVEYOR_REPO_TAG_NAME -and $env:APPVEYOR_REPO_TAG_NAME.StartsWith("test-v"))
      {
        buildVersion = "1.$($env:APPVEYOR_REPO_TAG_NAME.substring(6)).0.$($env:APPVEYOR_BUILD_NUMBER)"
      }
      Write-Host "Set version: '$buildBVersion'"
      Update-AppveyorBuild -Version "$buildVersion"
